"""Create users table

Revision ID: 0dcf1481aed6
Revises: 7b88bfcd7b52
Create Date: 2024-09-06 10:59:26.599920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dcf1481aed6'
down_revision = '7b88bfcd7b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
