"""Adicionar coluna cpf à tabela users

Revision ID: 6385dbe6a48e
Revises: bc6726bd74ad
Create Date: 2024-09-17 19:38:34.171087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6385dbe6a48e'
down_revision = 'bc6726bd74ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
