"""Adicionar coluna cpf à tabela users

Revision ID: bc6726bd74ad
Revises: b62519c22b7f
Create Date: 2024-09-17 19:38:26.184855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6726bd74ad'
down_revision = 'b62519c22b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
